#!/bin/bash

#Small bit of config here
#EDITOR=nano
#ECLevel=aes-256-cbc

#SVLocation=feature unused as of v2

##
#
# v2
#
# This is a simple text and file encryption frontend program.
# You can encrypt and decrypt [1] text files (made within this program)...
# [2] files, and [3] compress and encrypt archives (folders).
#
# This program has absolutely no warranty... things may break, so just follow along with instructions (Some failsafes have been made, just incase).
#
# This program uses aes-256-ccb, and aes-128-cbc as encryption algorithms via the openssl command.
#
# Yours, BobyMCbobs of https://github.com/BobyMCbobs
#
#        ________
#        < Enjoy! >
#        --------
#               \   ^__^
#                \  (oo)\_______
#                   (__)\       )\/\
#                      ||----w |
#                      ||     ||
#
##

eFCPath=$(dirname $0)
checkEditor=$(head -n 4 $eFCPath/easyfilecrypt | grep EDITOR= | cut -f2 -d '=')
progVer=$(head -n 11 $eFCPath/easyfilecrypt | tail -n 1 | awk {'print $2'})
encLvl=$(head -n 5 $eFCPath/easyfilecrypt | grep ECLevel= | cut -f2 -d '=')
SaveLocation=$(head -n 7 $eFCPath/easyfilecrypt | grep SVLocation= | cut -f2 -d '=')
TextViewer=$(head -n 6 $eFCPath/easyfilecrypt | grep TextViewer= | cut -f2 -d '=')
#windowSizeSmall=(8 78)
#windowSizeLarge=(15 60 8)

#function printWindowSize() {
#simple function to gen window sizes for whiptail
#arr=$1
#echo ${arr[*]}

#}

if [ ! `whoami` = "root" ]
then
	isRoot="sudo"
fi

menu() {

if [ -f edit-eFC.sh ]
then
	rm edit-eFC.sh
fi

OPTION=$(whiptail --title "Welcome to easyfilecrypt." --menu "Please choose your option" --backtitle "easyfilecrypt $progVer | using $checkEditor as text editor | $encLvl encryption level" --nocancel 15 60 8 \
"1" "Encrypt" \
"2" "Decrypt" \
"3" "Settings" \
"4" "Help" \
"5" "Exit"  3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]
then
	if [ $OPTION = 1 ]
	then
		encryptMain

	elif [ $OPTION = 2 ]
	then
		decryptMain

	elif [ $OPTION = 3 ]
	then
		configMain

	elif [ $OPTION  = 4 ]
	then
		helpMenu

	elif [ $OPTION = 6 ]
	then
		exit
	fi

else
	exit
fi

}

function encryptMain() {
#Encryption Menu

OPTION=$(whiptail --title "Encrypt menu." --menu "Please choose your option" --nocancel 15 60 8 \
"1" "Make text file" \
"2" "Use existing text file" \
"3" "Use normal file" \
"4" "Use a folder" \
"5" "Back"  3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]
then
	if [ $OPTION = 1 ]
	then
		makeTextFile

	elif [ $OPTION = 2 ]
	then
		encryptTextFile

	elif [ $OPTION = 3 ]
	then
		encryptFile

	elif [ $OPTION = 4 ]
	then
		encryptTar

	elif [ $OPTION = 5 ]
	then
		menu
	fi
else
	exit
fi


}


function makeTextFile() {
#Write message and encrypt

if [ $checkEditor = "nano" ]
then
	nano .encmsg.txt

elif [ $checkEditor = "vim" ]
then
	vim .encmsg.txt

fi

ckempt=$(du -h .encmsg.txt | cut -b 1)

nameFile

passCompare

cat .encmsg.txt | openssl $encLvl -a -salt -out $fileName -pass pass:$passPhrase
rm .encmsg.txt

menu

}

function nameFile() {
#Names the file that it will save it as

fileName=$(whiptail --inputbox "Give your file a full name:" 8 78 --title "File Name" --nocancel 3>&1 1>&2 2>&3)

}


function encryptTextFile() {
#Encrypt already existing text file
findTheFile=$(whiptail --inputbox "What's your text file's name?" 8 78 --title "File Name" --nocancel 3>&1 1>&2 2>&3)

if [ -f $findTheFile ]
then
        whiptail --title "Found file: '$findTheFile'" --msgbox "OK to continue" 8 78

	nameFile
	passCompare

	cat $findTheFile | openssl $encLvl -a -salt -out $fileName -pass pass:$passPhrase

	whiptail --title "'$fileName' saved." --msgbox "Press OK" 8 78

else
        whiptail --title "Could not find file: '$findTheFile'" --msgbox "Press OK to try again" 8 78

fi

}


function encryptFile() {
#Encrypt regular file
findTheFile=$(whiptail --inputbox "What's your file's name?" 8 78 --title "File Name" --nocancel 3>&1 1>&2 2>&3)

if [ -f $findTheFile ]
then
        whiptail --title "Found file: '$findTheFile'" --msgbox "OK to continue" 8 78

        nameFile
        passCompare

        openssl $encLvl -a -salt -in $findTheFile -out $fileName -pass pass:$passPhrase

        whiptail --title "'$fileName' saved." --msgbox "Press OK" 8 78

else
        whiptail --title "Could not find file: '$findTheFile'" --msgbox "Press OK to try again" 8 78

fi

}


function encryptTar() {
#Make archive of folder and encrypt
findTheFile=$(whiptail --inputbox "What's your folder's name?" 8 78 --title "Folder name" --nocancel 3>&1 1>&2 2>&3)

if [ -d $findTheFile ]
then
        nameFile
        tar -cvf .tmparch.tar $findTheFile

	if [ -f .tmparch.tar ]
	then

        	whiptail --title "Compression complete" --msgbox "Press OK" 8 78
        	passCompare
	        openssl $encLvl -a -salt -in .tmparch.tar -out $fileName -pass pass:$passPhrase

		if [ -f $fileName ]
		then

	        	rm .tmparch.tar
		        whiptail --title "Encryption complete" --msgbox "Press OK" 8 78

		fi
	fi

else
	whiptail --title "'$findTheFile' not found" --msgbox "Press OK" 8 78
	encryptTar

fi


}


function decryptMain() {
#Decryption Menu

OPTION=$(whiptail --title "Decrypt menu." --menu "Please choose your option" --nocancel 15 60 8 \
"1" "Use text file" \
"2" "    \-- Modify" \
"3" "Use normal file" \
"4" "Use a tar/archive" \
"5" "Change Encryption Key" \
"6" "Back"  3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]
then
	if [ $OPTION = 1 ]
	then
		decryptText

	elif [ $OPTION = 2 ]
	then
		modifyMain

	elif [ $OPTION = 3 ]
	then
		decryptFile

	elif [ $OPTION = 4 ]
	then
		decryptTar

	elif [ $OPTION = 5 ]
	then
		changeEncKey

        elif [ $OPTION = 6 ]
        then
                menu
        fi
else
        exit
fi


}

function decryptText() {
#decrypt text file

findName=$(whiptail --inputbox "You can use full directories, use extentions" 8 78 --title "What is the file name?" --nocancel 3>&1 1>&2 2>&3)
exitstatus=$?

if [ -f $findName ]
then

	if [ $exitstatus = 0 ]; then

		passPhrase=$(whiptail --passwordbox "Found '$findName'; Please enter the decryption key:" 8 78  --title "Decryption key" --nocancel 3>&1 1>&2 2>&3)
		exitstatus=$?

		if [ $exitstatus = 0 ]; then
			cat $findName | openssl $encLvl -a -d -salt -out .tempDec -pass pass:$passPhrase

			if [ -f .tempDec ]
			then
				isTempDecEmpty=$(du -h .tempDec | cut -b 1)
				if [ $isTempDecEmpty = "0" ]
				then
					whiptail --title "Error" --msgbox "Decryption failed." 8 78
					menu
				fi
			fi

	               	if (whiptail --title "Save" --yesno "Would you like to save?" 8 78)
			then
				fileName=$(whiptail --inputbox "What would you like to call it?" 8 78 --title "File Name" --nocancel 3>&1 1>&2 2>&3)
				cat .tempDec > $fileName
				viewDecryptedText
				rm .tempDec
				menu
			else

				viewDecryptedText
				rm .tempDec
				menu
			fi
		fi
	fi


else
	whiptail --title "Could not find file" --msgbox "Press OK to try again" 8 78
	decryptText

fi

}


function decryptFile() {
#decrypt a single file
findTheFile=$(whiptail --inputbox "What's your file's name?" 8 78 --title "File Name" --nocancel 3>&1 1>&2 2>&3)

if [ -f $findTheFile ]
then
        whiptail --title "Found file: '$findTheFile'" --msgbox "OK to continue" 8 78

        nameFile
        passPhrase=$(whiptail --passwordbox "Found '$findName'; Please enter the decryption key:" 8 78  --title "Decryption key" --nocancel 3>&1 1>&2 2>&3)

        openssl $encLvl -a -d -salt -in $findTheFile -out $fileName -pass pass:$passPhrase

        whiptail --title "'$fileName' has been decrypted" --msgbox "Press OK" 8 78

else
        whiptail --title "Could not find file: '$findTheFile'" --msgbox "Press OK to try again" 8 78
	decryptFile
fi

}


function decryptTar() {
#Decrypt an encrypted archive
findTheFile=$(whiptail --inputbox "What's your encrypted archive's name?" 8 78 --title "archive name" --nocancel 3>&1 1>&2 2>&3)

if [ -f $findTheFile ]
then

	passPhrase=$(whiptail --passwordbox "Found '$findTheFile'; Please enter the decryption key:" 8 78  --title "Decryption key" --nocancel 3>&1 1>&2 2>&3)
	openssl $encLvl -d -a -salt -in $findTheFile -out .tmparch.tar -pass pass:$passPhrase

        if [ -f .tmparch.tar ]
        then

		tar -xvf .tmparch.tar > /dev/null

                whiptail --title "Extraction complete" --msgbox "Press OK" 8 78

                if [ -f $fileName ]
                then

                        rm .tmparch.tar

                fi
        fi

else
        whiptail --title "'$findTheFile' not found" --msgbox "Press OK" 8 78
        decryptTar

fi

}


function viewDecryptedText() {
#View the text that was just decrypted

if (whiptail --title "View your text?" --yesno "View your decrypted message." 8 78)
then
   	#Yes
	whiptail --textbox .tempDec --scrolltext 20 78
fi

}


function changeEncKey() {
#Change the encryption key for any file

findTheFile=$(whiptail --inputbox "What's your file's name?" 8 78 --title "Text file name" 3>&1 1>&2 2>&3)

if [ -f $findTheFile ]
then
	whiptail --title "Found file '$findTheFile'" --msgbox "Press ok" 8 78
	passPhraseOld=$(whiptail --passwordbox "Please enter the current encryption key:" 8 78  --title "Encryption key" --nocancel 3>&1 1>&2 2>&3)
	passCompare

        openssl $encLvl -a -d -salt -in $findTheFile -pass pass:$passPhraseOld > .$findTheFile.enc
       	openssl $encLvl -a -salt -in .$findTheFile.enc -out $findTheFile.newpass -pass pass:$passPhrase
	
	if [ -f $findTheFile.newpass ]
	then
		mv $findTheFile.newpass $findTheFile; rm .$findTheFile.enc
		whiptail --title "'$findTheFile' now has new password" --msgbox "Press OK" 8 78
	else
		whiptail --title "ERROR.. something has gone wrong (probably crypto)"
	fi
fi

}

function modifyMain() {
#Modify text file menu
findTheFile=$(whiptail --inputbox "What's your text file's name?" 8 78 --title "Text file name" 3>&1 1>&2 2>&3)

if [ -f $findTheFile ]
then

	whiptail --title "'$findTheFile' found" --msgbox "Press OK" 8 78

	passPhrase=$(whiptail --passwordbox "Please enter the encryption key:" 8 78  --title "Encryption key" --nocancel 3>&1 1>&2 2>&3)

	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		echo
	else
		modifyMain
	fi

        openssl $encLvl -a -d -salt -in $findTheFile -out .modmsg.txt -pass pass:$passPhrase
        cat .modmsg.txt > .modmsgt.txt

	if [ $checkEditor = "nano" ]
	then
        	nano .modmsg.txt

	elif [ $checkEditor = "vim" ]
        then
		vim .modmsg.txt

	fi

        changes1=`cksum .modmsg.txt | awk -F" " '{print $1}'`
        changes2=`cksum .modmsgt.txt | awk -F" " '{print $1}' `

                if [ $changes1 = $changes2 ]
                then
			whiptail --title "No changes" --msgbox "Press OK to return" 8 78
                        rm .modmsg*.txt

                else

			whiptail --title "'$findTheFile' modified" --msgbox "Press OK to save" 8 78
                	openssl $encLvl -a -salt -in .modmsg.txt -out .modmsg2.txt -pass pass:$passPhrase

                        cat .modmsg2.txt > $findTheFile
                        rm .modmsg*.txt

                fi

else
	whiptail --title "'$findTheFile' not found" --msgbox "Press OK to return" 8 78

fi

}


function configMain(){
#Config Menu

checkEditor=$(head -n 4 $eFCPath/easyfilecrypt | grep EDITOR= | cut -f2 -d '=')
encLvl=$(head -n 5 $eFCPath/easyfilecrypt | grep ECLevel= | cut -f2 -d '=')

if [ -f edit-eFC.sh ]
then
        rm edit-eFC.sh
fi

configOPTION=$(whiptail --title "Config Menu" --menu "Change Settings?" --backtitle "Current Config: $checkEditor as Text Editor | $encLvl Encryption" --nocancel 25 78 16 \
"1" "Text editor" \
"2" "Encryption Level" \
"3" "Return to Menu" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]
then
	if [ $configOPTION == 1 ]
	then
		configTextEditor

	elif [ $configOPTION == 2 ]
	then
		configEncryptionLevel

	elif [ $configOPTION == 3 ]
	then
		menu
	fi

fi

}


function configEncryptionLevel() {
#Encryption level config

encLvl=$(head -n 5 $eFCPath/easyfilecrypt | grep ECLevel= | cut -f2 -d '=')

if [ $encLvl = "aes-128-cbc" ]
then
        local defaultOptionOff=""

elif [ $encLvl = "aes-256-cbc" ]
then
        local defaultOptionOff="--defaultno"
fi

if (whiptail --title "Set Encryption Level" --yesno "Choose the prefered Encryption Level (current is $encLvl)" --yes-button "aes-256-cbc" --no-button "aes-128-cbc" $defaultOptionOff 8 78)
then
	if [ $encLvl = "aes-128-cbc" ]
	then
                echo "sed -i -e '5s/#ECLevel=aes-128-cbc/#ECLevel=aes-256-cbc/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
                echo '$isRoot whiptail --title "aes-256-cbc set" --msgbox "Press OK to continue" 8 78' >> edit-eFC.sh
                bash edit-eFC.sh
                rm edit-eFC.sh
		configMain
	else
		configMain
	fi

else
        if [ $encLvl = "aes-256-cbc" ]
        then
                echo "sed -i -e '5s/#ECLevel=aes-256-cbc/#ECLevel=aes-128-cbc/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
                echo '$isRoot whiptail --title "aes-128-cbc set" --msgbox "Press OK to continue" 8 78' >> edit-eFC.sh
                bash edit-eFC.sh
                rm edit-eFC.sh
                configMain
        else
                configMain
        fi



fi
}


function configConfigLocation() {
#Menu for where to save config - unused as of v2

if (whiptail --title "Location for Config" --yesno "Where should config for easyfilecrypt be saved?" --yes-button "In easyfilecrypt" --no-button "Outside Config" 8 78)
then
	if [ $SaveLocation = "outsideconfig" ]
	then
                echo "sed -i -e '7s/#SVLocation=outsideconfig/#SVLocation=inscript/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
                echo 'whiptail --title "Config will now save in $eFCPath/easyfilecrypt" --msgbox "Press OK to continue" 8 78' >> edit-eFC.sh
                bash edit-eFC.sh
                rm edit-eFC.sh
		configMain

	elif [ $SaveLocation = "notconfigured" ]
	then
		echo "sed -i -e '7s/#SVLocation=notconfigured/#SVLocation=inscript/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
                echo 'whiptail --title "Config will now save in $eFCPath/easyfilecrypt" --msgbox "Press OK to continue" 8 78' >> edit-eFC.sh
                bash edit-eFC.sh
                rm edit-eFC.sh
		menu
	else
		configMain
	fi

	if [ -f /usr/local/etc/easyfilecrypt.config ]
	then
		sudo rm /usr/local/etc/easyfilecrypt.config
	fi

else
        if [ $SaveLocation = "inscript" ]
        then
                echo "sed -i -e '7s/#SVLocation=inscript/#SVLocation=outsideconfig/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
                echo 'whiptail --title "Config will now save in /usr/local/etc/easyfilecrypt.config" --msgbox "Press OK to continue" 8 78' >> edit-eFC.sh
                bash edit-eFC.sh
                rm edit-eFC.sh
		configMain
	elif [ $SaveLocation = "notconfigured" ]
	then
		echo "sed -i -e '7s/#SVLocation=notconfigured/#SVLocation=outsideconfig/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
                echo 'whiptail --title "Config will now save in /usr/local/etc/easyfilecrypt.config" --msgbox "Press OK to continue" 8 78' >> edit-eFC.sh
                bash edit-eFC.sh
                rm edit-eFC.sh
		menu

        else
                configMain
        fi

	if [ ! -f /usr/local/etc/easyfilecrypt.config ]
	then
		sudo touch /usr/local/etc/easyfilecrypt.config
		sudo chmod 0755 /usr/local/etc/easyfilecrypt.config
		sudo head -n 5 $eFCPath/easyfilecrypt | tail -n 3 > /usr/local/etc/easyfilecrypt.config
	fi

fi

}


function configTextEditor() {
#Tune up easyfilecrypt to how you like it
checkEditor=$(head -n 4 $eFCPath/easyfilecrypt | grep EDITOR= | cut -f2 -d '=')

if [ $checkEditor = "vim" ]
then
	local defaultOptionOff=""

elif [ $checkEditor = "nano" ]
then
	local defaultOptionOff="--defaultno"
fi


if (whiptail --title "Set Text Editor" --yesno "Choose your Text Editor (current is: $checkEditor)" --yes-button "Nano" --no-button "Vim" $defaultOptionOff 8 78)
then

	if [ $checkEditor = "vim" ]
	then
		isNotRootPleaseSudo
		echo "$isRoot sed -i -e '4s/#EDITOR=vim/#EDITOR=nano/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
		echo 'whiptail --title "Nano set" --msgbox "Press OK to continue" 8 78' >> edit-eFC.sh
		bash edit-eFC.sh
		rm edit-eFC.sh
		checkEditor=$(head -n 4 $eFCPath/easyfilecrypt | grep EDITOR= | cut -f2 -d '=')
		configMain
	else
		configMain

	fi
else

	if [ $checkEditor = "nano" ]
	then
		if [ ! -f /usr/bin/vim ]
		then
			if (whiptail --title "Install Vim?" --yesno "Would you like to install Vim?" 8 78)
			then
				sudo apt install vim -y
			else
				exit
			fi
		fi

		isNotRootPleaseSudo
		echo "$isRoot sed -i -e '4s/#EDITOR=nano/#EDITOR=vim/g' $eFCPath/easyfilecrypt" >> edit-eFC.sh
		echo 'whiptail --title "Vim set" --msgbox "Press OK to continue" 8 78' >>  edit-eFC.sh
       	 	bash edit-eFC.sh
		rm edit-eFC.sh
		checkEditor=$(head -n 4 $eFCPath/easyfilecrypt | grep EDITOR= | cut -f2 -d '=')
		configMain
	else
		configMain

	fi
fi

}

function helpMenu() {
#print help guide STILL WORKING PROGRESS
helpText="Welcome to easyFileEncrypt!

1. Encrypting and Decrypting data
	- Text Files
		- Creating a new text file
			- Simply let the text editor open 
	- Regular Files
		- Select a file to encrypt, give it a name for the encrypted version
	- Archives
		- Select a directory to compress then encrypt

2. Modifying data
	- Text Files
		- Select your text file, then perform and edit on it
	- Change encryption key

3. Settings
	- Change the text editor to either nano, or vim.
	- Change encryption level either to AES-(256 or 125)-cbc

"
whiptail --textbox /dev/stdin 40 80 --scrolltext <<< "$helpText"

menu

}


function passCompare {
#compare passwords to encrypt files and users type; declear passPhrase variable

#1st
passPhrase=$(whiptail --passwordbox "Please enter the new encryption key:" 8 78  --title "Encryption key" 3>&1 1>&2 2>&3)

#2nd
passPhrase2=$(whiptail --passwordbox "Please repeat the new encryption key:" 8 78  --title "Encryption key" 3>&1 1>&2 2>&3)

if [ "$passPhrase" = "$passPhrase2" ]
then
        whiptail --title "Passphrases match... continuing" --msgbox "Press OK to continue" 8 78
	#whiptail --textbox itWorkedBoxPF 8 78
else
        whiptail --title "Passphrases do not match, please try again." --msgbox "Press OK to redo" 8 78
	passCompare
fi

}

function initalSetup() {
#easyfilecrypt inital setup
whiptail --title "Welcome to easyfilecrypt" --msgbox "Press Ok to setup" 8 78

configConfigLocation

}

function checkRequirements() {
#install programs that help this to run
if [ ! -f /usr/bin/whiptail ] || [ ! -f /usr/bin/openssl ]
then
	if (whiptail --title "whiptail, or openssl seams not to be installed" --yesno "Do you want to install them?" 8 78)
	then
		sudo apt install -y whiptail openssl nano
	else
		exit
	fi
fi

}

function isNotRootPleaseSudo() {
#message to enter your password to modify how this program works

if [ ! $isRoot = "root" ] && [ $eFCPath = "/usr/*"  ]
then
	echo "You may be required to enter your password to change this setting"
fi

}

checkRequirements
menu
